language: node_js
node_js:
  - "12"
  - "10"
before_script:
  - npm install
notifications:
  email:
    - vic@smalldata.tech
after_script: istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly --opts server/mocha.opts 'server/**/*.test.js' -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
