language: node_js
node_js:
  - "12"
  - "10"
env:
  - NODE_ENV=test
before_script:
  - npm install
  - cp .env.dist .env
script:
  - npm run server:test
notifications:
  email:
    - vic@smalldata.tech
after_script: npm run istanbul
